version: 2.1

orbs:
  cypress: cypress-io/cypress@3.3.1

jobs:
  start-server:
        docker:
          - image: cypress/base:latest
        steps:
          - checkout
          - run:
              name: Install dependencies
              command: npm install
          - run:
              name: Build the app
              command: npm run build
  deploy-to-render-staging:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Deploy to Render Staging
          # TODO: What is happening in the following command?
          # This command is sending a POST request to the Render Staging deploy hook
          command: |
            echo "Deploying to Render Staging"
            curl $RENDER_STAGING_DEPLOYHOOK

workflows:
  run-tests-and-deploy-to-staging:
    jobs:
      - start-server
      - cypress/run:
          name: run-component-tests
          cypress-command: npx cypress run --component
      - deploy-to-render-staging:
          # TODO: What does the requires key do?
          # wait for the previous jobs to finish before running this job
          requires:
            - run-component-tests
          # TODO: What does the filters key do?
          # only run this job when the branch is main
          filters:
            branches:
              only: main
